# Misc tasks.

namespace :pre do
  SASS_DIR = "views/sass"
  CSS_DIR = "public/css"

  desc "Convert sass source files to css files"
  task :convert_sass do
    Dir.glob("#{SASS_DIR}/*.sass") do |f|
      file_name = File.basename f, ".sass"
      dest_file = "#{CSS_DIR}/#{file_name}.css"
      File.delete dest_file if File.exists? dest_file
      sh "sass #{f} #{dest_file}"
    end
  end


  COFFEE_DIR = "views/coffee"
  JS_DIR = "public/js"

  desc "Convert sass source files to css files"
  task :convert_coffee do
    Dir.glob("#{COFFEE_DIR}/*.coffee") do |f|
      file_name = File.basename f, ".coffee"
      dest_file = "#{CSS_DIR}/#{file_name}.js"
      File.delete dest_file if File.exists? dest_file
      sh "coffee #{f} #{dest_file}"
    end
  end

  desc "Master job for pre-processing."
  task convert: [:convert_sass, :convert_coffee] do
    puts "Preprocessing completed."
  end
end
